### ISSUE TITLE
Allow to customize the emoji size for the Popup

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#173]
This includes the normal popup as well as the variant popup.

**Comment by searchy2** [comment]
I would like to hear your thoughts on how this could be implemented. You are against setting a fixed number of emoticons per row as the method of implementation. However, I believe that is the appropriate way to manage the size of the emoticons. The reason is that GridView is responsible for managing the size of its items. GridView automatically resizes items based on the number of items in each row. There is no need for you to calculate sizes manually when GridView does the work for you. What do you think?

**Comment by vanniktech** [comment]
You'd pass the wanted emoji size into the EmojiPopup builder and this would pass it down into the views.

**Comment by vanniktech** [comment]
@searchy2 want to contribute this feature?
