### ISSUE TITLE
Adding support for gif animations?

### ISSUE THREAD

**Issue by BennieBe** [vanniktech/Emoji#416]
Hi there,

Is it possible to add gif animations instead of emojicons into the different category tabs?
If yes, a small example where to look and how to achieve this would be helpful :)

Thanks!

**Comment by rubengees** [comment]
The categories have `Emoji` instances which return `Drawable`s. It might be possible to add a custom `Emoji` class in a category, which returns `AnimationDrawable`s or some gif `Drawable` implementation.

This would most likely require changes on the library though, since one has to start the animation of the `Drawable` iirc.

Please go ahead and explore if you like :).

**Comment by BennieBe** [comment]
Hi @rubengees,

Thanks for the information! 
I think I will try to extend the the lib to support animations and make a PR for it!

**Comment by BennieBe** [comment]
Hi @rubengees,

So I got to the point where I am having the necessary data to show the animation in the chat view.
I got stuck though during the part where you draw the animation. Somehow the bitmap frames (using an AnimationDrawable) do not get passed and I cannot find the issue. Is it possible for me to create a branch and make a commit here?

**Comment by rubengees** [comment]
You can fork the project and make a (draft) PR :)

**Comment by BennieBe** [comment]
Hi @rubengees,

I created a draft PR. I might have accidentally forgotten to add reviewers ;)
Anyways, I would appreciate if someone could have a look at it!
